### ISSUE TITLE
Prepare to release the plugin to clients using Github releases

### ISSUE THREAD

**Issue by bricollins** [reachlocal/reachedge-wordpress-4x-tracking-plugin#4]
Story: https://github.com/reachlocal/reach-edge/issues/22

- [x] [Establish a Github release for the plugin according to guidelines] (https://github.com/blog/1547-release-your-software)
- [x] Create a Wordpress account

**Comment by cyphactor** [comment]
This might help:

https://github.com/blog/1178-collaborating-on-github-with-subversion

Or this:

https://help.github.com/articles/support-for-subversion-clients/

**Comment by jwreachlocal** [comment]
![screen shot 2015-03-16 at 2 36 38 pm](https://cloud.githubusercontent.com/assets/3331444/6677070/f97fb076-cbe9-11e4-9f24-f80b29cf19f7.png)

**Comment by adamlcolson** [comment]
me for now. I think I can add more email addresses if needed.

**Comment by jwreachlocal** [comment]
#### From Adam

The slug for the plugin should be changed to https://wordpress.org/plugins/reachlocal-tracking/

Text changes:

https://github.com/reachlocal/reachedge-wordpress-4x-tracking-plugin/blob/reword/README.txt#L1
* Change line to: === ReachLocal ===

https://github.com/reachlocal/reachedge-wordpress-4x-tracking-plugin/blob/reword/README.txt#L3
* Add the following tags to this line: reach local, reach edge, capture

https://github.com/reachlocal/reachedge-wordpress-4x-tracking-plugin/blob/reword/README.txt#L10
* Change line to: Adds ReachLocal's tracking code on all pages.

https://github.com/reachlocal/reachedge-wordpress-4x-tracking-plugin/blob/reword/README.txt#L14
* Change line to: This plugin adds the required javascript code on all pages in order to track analytics and enable other features for the [ReachEdge](http://go.reachlocal.com/contact-us-edge.html) product and other ReachLocal digital marketing solutions.

**Comment by jwreachlocal** [comment]
Submitted another request to WordPress.

![screen shot 2015-03-19 at 11 52 51 am](https://cloud.githubusercontent.com/assets/3331444/6738321/83b8aae0-ce2e-11e4-9bbb-a2bd9a4515a1.png)

**Comment by jwreachlocal** [comment]
```
---------- Forwarded message ----------
From: "WordPress.org" <plugins@wordpress.org>
Date: Mar 19, 2015 6:43 PM
Subject: [WordPress.org Plugins] Request: reachlocal-tracking-code
To: <adam.colson@reachlocal.com>
Cc: 

## PHP Short Tags

You're using PHP Short Tags

<script type="text/javascript">var rl_siteid = "<?= $reachlocal_tracking_id ?>";</script>

The primary issue with PHP's short tags is that PHP managed to choose a tag (<?) that was used by another syntax, XML.

With the option enabled, you weren't able to raw output the xml declaration without getting syntax errors:

<?xml version="1.0" encoding="UTF-8" ?>

This is a big issue when you consider how common XML parsing and management is.

While as of PHP 5.4, <?= ... ?> tags are supported everywhere, regardless of short tags settings. This should mean they're safe to use in portable code but that does mean there's then a dependency on PHP 5.4+. If you want to support pre-5.4 and can't guarantee short tags, you'll still need to use <?php echo ... ?>.

At this time, we ask that no plugin use PHP short tags, for sanity.

## Please use wp_enqueue commands

Your plugin is using <style> and/or <link> tags to insert CSS/JS

<script type="text/javascript" src="//cdn.rlets.com/capture_static/mms/mms.js" async="async"></script>

You should be using the built in functions for this:

https://codex.wordpress.org/Function_Reference/wp_enqueue_script
https://codex.wordpress.org/Function_Reference/wp_enqueue_style

If you're trying to enqueue on the admin pages you'll want to use the admin enqueues

https://codex.wordpress.org/Plugin_API/Action_Reference/admin_enqueue_scripts
https://codex.wordpress.org/Plugin_API/Action_Reference/admin_print_scripts
https://codex.wordpress.org/Plugin_API/Action_Reference/admin_print_styles

## Generic function (and/or define) names

All plugins should have unique function names, defines, and classnames. This will prevent your plugin from conflicting with other plugins or themes.

For example, if your plugin is called "Easy Custom Post Types", then you might prefix your functions with ecpt_{your function name here}. Similarly a define of LICENSE would be better done as ECPT_LICENSE.

Please update your plugin to use more unique names.

tracking_code_id is not a very unique option.


When you've corrected your code, reply to this email with the updated code attached as a zip, or provide a link to the new code for us to review.
```

Looks like we have some changes we need to make.
